import { MembraneMode, PresetConfig } from '../types';

export const PRESETS: Record<MembraneMode, PresetConfig> = {
  prismatic: {
    name: 'prismatic',
    label: 'Prismatic Glass',
    description: 'High-index optical glass with pronounced spectral chromatic dispersion and crisp specular highlights.',
    colorAccent: '#60A5FA',
    params: {
      stiffness: 0.45,
      damping: 0.982,
      viscosity: 0.12,
      tension: 0.85,
      impulseStrength: 1.2,
      refractionStrength: 0.045,
      dispersionStrength: 0.022,
      specularPower: 48.0,
      fresnelPower: 1.8,
      ambientUndulation: 0.008,
    },
  },
  mercury: {
    name: 'mercury',
    label: 'Liquid Mercury',
    description: 'Dense metallic fluid with deep curvature, high surface tension, and reflective chrome sheen.',
    colorAccent: '#E5E7EB',
    params: {
      stiffness: 0.52,
      damping: 0.975,
      viscosity: 0.28,
      tension: 1.15,
      impulseStrength: 1.6,
      refractionStrength: 0.075,
      dispersionStrength: 0.006,
      specularPower: 80.0,
      fresnelPower: 2.8,
      ambientUndulation: 0.012,
    },
  },
  frosted: {
    name: 'frosted',
    label: 'Frosted Silica',
    description: 'Silky, diffuse translucent membrane with gentle wave propagation and soft light scattering.',
    colorAccent: '#9CA3AF',
    params: {
      stiffness: 0.32,
      damping: 0.965,
      viscosity: 0.45,
      tension: 0.65,
      impulseStrength: 0.85,
      refractionStrength: 0.028,
      dispersionStrength: 0.010,
      specularPower: 16.0,
      fresnelPower: 1.2,
      ambientUndulation: 0.004,
    },
  },
  iridescent: {
    name: 'iridescent',
    label: 'Thin-Film Pearl',
    description: 'Anisotropic soap-bubble membrane with dynamic wavelength interference and chromatic phase shifts.',
    colorAccent: '#F472B6',
    params: {
      stiffness: 0.40,
      damping: 0.986,
      viscosity: 0.18,
      tension: 0.78,
      impulseStrength: 1.1,
      refractionStrength: 0.052,
      dispersionStrength: 0.035,
      specularPower: 64.0,
      fresnelPower: 3.2,
      ambientUndulation: 0.010,
    },
  },
};
